"use client";

import { notFound } from "next/navigation";
import { ArrowRight, Linkedin, Search, X } from "lucide-react";
import { useMemo, useState } from "react";
import { useDemo, speakerName } from "@/shared/demo/demo-provider";
import { Avatar } from "@/shared/ui/ui-kit";
import { PublicEventShell, DEFAULT_EMBED_OPTIONS, type EmbedOptions } from "./public-event-shell";

export function PublicSpeakers({eventSlug,embed=false,embedOptions=DEFAULT_EMBED_OPTIONS}:{eventSlug:string;embed?:boolean;embedOptions?:EmbedOptions}){const{state,hydrated}=useDemo();const[search,setSearch]=useState("");const event=state.events.find((item)=>item.slug===eventSlug);const speakers=useMemo(()=>state.speakers.filter((speaker)=>speaker.eventId===event?.id&&speaker.confirmation==="confirmed"&&`${speakerName(speaker)} ${speaker.company} ${speaker.tags.join(" ")}`.toLowerCase().includes(search.toLowerCase())),[search,state.speakers,event?.id]);if(!event){if(!hydrated)return null;notFound()}return <PublicEventShell active="speakers" event={event} embed={embed} embedOptions={embedOptions}><main className={`public-speakers ${embed?"embed-content":"public-event-container"}`}><header><div><span className="public-eyebrow">MEET THE COMMUNITY</span><h2>People shaping<br/>what comes next.</h2></div><p>Learn from the engineers, researchers, founders, and designers building the AI-native world.</p></header><label className="speaker-search"><Search size={18}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search speakers, companies, or topics"/>{search&&<button onClick={()=>setSearch("")}><X size={15}/></button>}</label><div className="speaker-gallery">{speakers.map((speaker,index)=><article key={speaker.id} className={index===0&&!embed?"featured":""}><div className="speaker-portrait" style={{background:`linear-gradient(145deg,${speaker.avatarColor},#17152a)`}}><Avatar initials={speaker.avatar} color="rgba(255,255,255,.14)" size="xl"/>{speaker.tags.includes("Keynote")&&<span>KEYNOTE</span>}</div><div><h3>{speakerName(speaker)}</h3><p>{speaker.title} · {speaker.company}</p><small>{speaker.bio}</small><div className="speaker-topics">{speaker.tags.map((tag)=><span key={tag}>{tag}</span>)}</div><footer><Linkedin size={15}/><button>View sessions <ArrowRight size={14}/></button></footer></div></article>)}</div></main></PublicEventShell>}
