"use client";

import { Clock3, Edit3, FileText, MapPin } from "lucide-react";
import { useState } from "react";
import { useDemo } from "@/shared/demo/demo-provider";
import { DEMO_SPEAKER_ID } from "@/shared/demo/seed";
import { Button, Field, Modal, StatusBadge } from "@/shared/ui/ui-kit";
import { useToast } from "@/shared/ui/toast";

export function PortalSubmissions(){const{state,dispatch}=useDemo();const{toast}=useToast();const[editId,setEditId]=useState<string|null>(null);const submissions=state.submissions.filter((item)=>item.speakerIds.includes(DEMO_SPEAKER_ID));const active=submissions.find((item)=>item.id===editId);const[title,setTitle]=useState("");function open(id:string){const item=submissions.find((submission)=>submission.id===id);setEditId(id);setTitle(item?.title??"")}function save(){if(active){dispatch({type:"UPDATE_SUBMISSION",submissionId:active.id,patch:{title,updatedAt:new Date().toISOString()}});toast("Proposal updated")}setEditId(null)}return <div className="portal-container portal-page"><header className="portal-page-header"><span className="public-eyebrow">MY PROGRAM</span><h1>My submissions</h1><p>Review your proposals and scheduled sessions.</p></header><div className="portal-submission-grid">{submissions.map((submission)=>{const session=state.sessions.find((item)=>item.submissionId===submission.id);return <article className="portal-submission" key={submission.id}><header><span className="portal-doc-icon"><FileText size={21}/></span><div><span>{submission.code}</span><StatusBadge value={submission.status}/></div></header><h2>{submission.title}</h2><p>{submission.abstract}</p><div className="portal-tags"><span>{submission.track}</span><span>{submission.format}</span></div>{session?.startsAt&&<div className="portal-scheduled"><b>Your session is scheduled</b><span><Clock3 size={14}/>{new Date(session.startsAt).toLocaleString("en-US",{month:"long",day:"numeric",hour:"numeric",minute:"2-digit"})}</span><span><MapPin size={14}/>{session.room}</span></div>}<footer><span>Updated August 7</span><Button size="sm" variant="secondary" onClick={()=>open(submission.id)}><Edit3 size={14}/> Edit proposal</Button></footer></article>})}</div><Modal open={Boolean(active)} onClose={()=>setEditId(null)} title="Edit your proposal" description="Changes are allowed until the call closes on August 31." footer={<><Button variant="secondary" onClick={()=>setEditId(null)}>Cancel</Button><Button onClick={save}>Save changes</Button></>}><div className="form-stack"><Field label="Session title"><input value={title} onChange={(e)=>setTitle(e.target.value)}/></Field><Field label="Abstract"><textarea defaultValue={active?.abstract}/></Field><div className="setting-note"><Clock3 size={18}/><div><b>Editing closes August 31 at 11:59 PM PDT</b><p>After the deadline, contact the organizing team for changes.</p></div></div></div></Modal></div>}
