"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, FileText, MapPin, Presentation, Search } from "lucide-react";
import { useDemo } from "@/shared/demo/demo-provider";
import { RichTextView } from "@/shared/ui/app/rich-text-view";

const icons=[BookOpen,Presentation,MapPin];export function PortalResources(){const{state}=useDemo();return <div className="portal-container portal-page"><header className="portal-page-header"><span className="public-eyebrow">SPEAKER HUB</span><h1>Resources</h1><p>Guides and event information from the organizing team.</p></header><label className="portal-resource-search"><Search size={18}/><input placeholder="Search resources"/></label><div className="portal-resource-grid">{state.resources.filter((item)=>item.published).map((resource,index)=>{const Icon=icons[index%icons.length]??FileText;return <Link href={`/portal/ai-engineer/resources/${resource.slug}`} key={resource.id}><span><Icon size={23}/></span><small>GUIDE</small><h2>{resource.title}</h2><p>{resource.summary}</p><b>Read guide <ArrowRight size={14}/></b></Link>})}</div></div>}
export function PortalResourceDetail({slug}:{slug:string}){const{state}=useDemo();const resource=state.resources.find((item)=>item.slug===slug);if(!resource)return <div className="empty-state"><h3>Resource not found</h3></div>;return <div className="portal-container resource-detail-page"><Link href="/portal/ai-engineer/resources"><ArrowLeft size={15}/> All resources</Link><article><span className="public-eyebrow">SPEAKER RESOURCE</span><h1>{resource.title}</h1><p className="resource-summary">{resource.summary}</p><RichTextView html={resource.body} wide/><div className="resource-contact"><b>Still have a question?</b><p>Our speaker success team is happy to help.</p><a href="mailto:speakers@ai.engineer">Contact speaker support</a></div></article></div>}
