"use client";

import Link from "next/link";
import { Bell, BookOpen, CalendarDays, ChevronDown, ClipboardCheck, Home, Menu, UserRound, X } from "lucide-react";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { useDemo } from "@/shared/demo/demo-provider";
import { usePortal } from "./portal-context";
import { Avatar } from "@/shared/ui/ui-kit";
import { ImpersonationBanner } from "@/features/auth/components/impersonation-banner";

const links=[{label:"Home",href:"",icon:Home},{label:"My submissions",href:"submissions",icon:CalendarDays},{label:"Tasks",href:"tasks",icon:ClipboardCheck},{label:"Profile",href:"profile",icon:UserRound},{label:"Resources",href:"resources",icon:BookOpen}];
export function PortalShell({children}:{children:React.ReactNode}){const pathname=usePathname();const{state}=useDemo();const{event,speaker,impersonated,exitImpersonation}=usePortal();const[open,setOpen]=useState(false);const base=`/portal/${event.slug}`;const openTasks=state.tasks.filter((task)=>task.eventId===event.id&&!state.completions.some((done)=>done.taskId===task.id&&done.speakerId===speaker.id)).length;return <div className="portal-shell">{impersonated&&<ImpersonationBanner name={`${speaker.firstName} ${speaker.lastName}`} email={speaker.email} backHref={`/events/${event.id}/speakers/${speaker.id}`} onExit={exitImpersonation}/>}<header className="portal-header"><div className="portal-container"><button type="button" className="portal-mobile-menu" aria-label={open?"Close navigation":"Open navigation"} onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button><Link href={base} className="portal-event-brand"><span className="public-event-logo">AI<span>.engineer</span></span><i/><small>Speaker Portal</small></Link><nav className={open?"open":""}>{links.map((item)=>{const Icon=item.icon;const href=item.href?`${base}/${item.href}`:base;const active=item.href?pathname.includes(`/${item.href}`):pathname===base;return <Link key={item.label} href={href} className={active?"active":""} onClick={()=>setOpen(false)}><Icon size={16}/>{item.label}{item.href==="tasks"&&openTasks>0&&<span>{openTasks}</span>}</Link>})}</nav><div className="portal-account"><button type="button" className="icon-button notification-button" aria-label="Notifications"><Bell size={18}/><i/></button><Avatar initials={speaker.avatar} color={speaker.avatarColor}/><span><b>{speaker.firstName}</b><small>Speaker</small></span><ChevronDown size={15}/></div></div></header><main className="portal-main">{children}</main><footer className="portal-site-footer"><div className="portal-container"><span>{event.name}</span><div><a href="mailto:speakers@ai.engineer">Get help</a><Link href={`/e/${event.slug}/schedule`}>Public schedule</Link><span>Powered by Openboard</span></div></div></footer></div>}
