"use client";

import { BookOpen, ExternalLink, FileText, MoreHorizontal, Plus } from "lucide-react";
import { useState } from "react";
import { useDemo } from "@/shared/demo/demo-provider";
import { Button, Field, Modal, PageHeader, StatusBadge } from "@/shared/ui/ui-kit";
import { useToast } from "@/shared/ui/toast";
import { slugify } from "@/shared/lib/slug";

export function ResourcesAdminPage(){const{state,dispatch}=useDemo();const{toast}=useToast();const[creating,setCreating]=useState(false);const[title,setTitle]=useState("");const[body,setBody]=useState("");function create(){if(!title.trim())return;dispatch({type:"ADD_RESOURCE",resource:{id:`res_${Date.now()}`,eventId:state.events[0]?.id??"",title,slug:slugify(title),summary:"Helpful information for event speakers.",body:`<h2>${title}</h2><p>${body}</p>`,published:true}});setCreating(false);setTitle("");setBody("");toast("Resource published to the portal")}return <><PageHeader eyebrow="ENGAGE" title="Resources" description="Publish a useful, searchable speaker handbook inside the portal." actions={<Button onClick={()=>setCreating(true)}><Plus size={16}/> New page</Button>}/><div className="resource-admin-layout"><section className="panel resource-list-admin"><header className="panel-header"><div><h2>Speaker resources</h2><p>{state.resources.length} published pages</p></div></header>{state.resources.map((resource,index)=><article key={resource.id}><span className="resource-doc"><FileText size={20}/></span><div><div><h3>{resource.title}</h3><StatusBadge value={resource.published?"Published":"Draft"}/></div><p>{resource.summary}</p><small>Updated {index+2} days ago · /{resource.slug}</small></div><a className="icon-button" href={`/portal/ai-engineer/resources/${resource.slug}`} target="_blank"><ExternalLink size={17}/></a><button className="icon-button"><MoreHorizontal size={17}/></button></article>)}</section><aside className="resource-tip"><span><BookOpen size={20}/></span><h3>Build a speaker-ready hub</h3><p>Use resource pages for travel, stage logistics, presentation guidelines, and embedded maps or videos.</p><ul><li>Rich text and secure links</li><li>Responsive embeds</li><li>Portal-only visibility</li></ul></aside></div><Modal open={creating} onClose={()=>setCreating(false)} title="Create resource page" description="This page will appear in the speaker portal." footer={<><Button variant="secondary" onClick={()=>setCreating(false)}>Cancel</Button><Button disabled={!title.trim()} onClick={create}>Publish page</Button></>}><div className="form-stack"><Field label="Page title" required><input autoFocus value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="e.g. Speaker dinner details"/></Field><Field label="Body"><textarea value={body} onChange={(e)=>setBody(e.target.value)} placeholder="Add the information speakers need…"/></Field><Field label="Embed URL" hint="Optional. HTTPS video and map embeds are allowed only on resource pages."><input type="url" placeholder="https://…"/></Field></div></Modal></>}
