/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.wrangler/typegen-empty.env --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: ca19cc584e27b65b131dc7b0d5d77de3)
interface __BaseEnv_CloudflareEnv {
	FILES: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	APP_ENV: "preview" | "production" | "local";
	BETTER_AUTH_URL?: "https://sb-web-preview.yi-ding.workers.dev" | "https://openboard.events";
	BILLING_MODE: "disabled";
	EMAIL_MODE: "send" | "log";
	EMAIL_FROM?: "AI.Engineer Sandbox <hello@mail.openboard.events>";
	EMAIL_ALLOWLIST?: "yi.s.ding@gmail.com";
	EMAIL_FALLBACK_UI: "1" | "0";
	AIRTABLE_CRON: "0";
	NEXT_INC_CACHE_R2_PREFIX: "open-next-cache";
	R2_BUCKET_NAME: "sb-files-preview" | "sb-files" | "sb-files-dev";
	WORKER_SELF_REFERENCE: Fetcher /* sb-web-preview */ | Fetcher /* sb-web */ | Fetcher /* sb-web-local */;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		FILES: R2Bucket;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		APP_ENV: "preview";
		BETTER_AUTH_URL: "https://sb-web-preview.yi-ding.workers.dev";
		BILLING_MODE: "disabled";
		EMAIL_MODE: "send";
		EMAIL_FROM: "AI.Engineer Sandbox <hello@mail.openboard.events>";
		EMAIL_ALLOWLIST: "yi.s.ding@gmail.com";
		EMAIL_FALLBACK_UI: "1";
		AIRTABLE_CRON: "0";
		NEXT_INC_CACHE_R2_PREFIX: "open-next-cache";
		R2_BUCKET_NAME: "sb-files-preview";
		WORKER_SELF_REFERENCE: Fetcher /* sb-web-preview */;
	}
	interface ProductionEnv {
		FILES: R2Bucket;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		APP_ENV: "production";
		BETTER_AUTH_URL: "https://openboard.events";
		BILLING_MODE: "disabled";
		EMAIL_MODE: "send";
		EMAIL_FROM: "AI.Engineer Sandbox <hello@mail.openboard.events>";
		EMAIL_FALLBACK_UI: "0";
		AIRTABLE_CRON: "0";
		NEXT_INC_CACHE_R2_PREFIX: "open-next-cache";
		R2_BUCKET_NAME: "sb-files";
		WORKER_SELF_REFERENCE: Fetcher /* sb-web */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "BETTER_AUTH_URL" | "BILLING_MODE" | "EMAIL_MODE" | "EMAIL_FROM" | "EMAIL_ALLOWLIST" | "EMAIL_FALLBACK_UI" | "AIRTABLE_CRON" | "NEXT_INC_CACHE_R2_PREFIX" | "R2_BUCKET_NAME">> {}
}
