/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.wrangler/google-signin-typegen-empty.env --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: da19cc69d324d705ca8fe0b7ada64d63)
interface __BaseEnv_CloudflareEnv {
	FILES: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	APP_ENV: "preview" | "production" | "local";
	ADMIN_AUTH_PROVIDER?: "better-auth";
	BETTER_AUTH_URL?: "https://sb-web-preview.yi-ding.workers.dev" | "https://sb-web.yi-ding.workers.dev";
	BILLING_MODE: "disabled";
	EMAIL_MODE: "send" | "log";
	EMAIL_FROM?: "AI.Engineer Sandbox <hello@mail.openboard.events>";
	EMAIL_ALLOWLIST?: "yi.s.ding@gmail.com";
	EMAIL_FALLBACK_UI: "1" | "0";
	AIRTABLE_CRON: "0";
	NEXT_INC_CACHE_R2_PREFIX: "open-next-cache";
	R2_BUCKET_NAME: "sb-files-preview" | "sb-files" | "sb-files-dev";
	TEST_AUTH?: "1";
	WORKER_SELF_REFERENCE: Fetcher /* sb-web-preview */ | Fetcher /* sb-web */ | Fetcher /* sb-web-local */;
}
declare namespace Cloudflare {
	interface PreviewEnv {
		FILES: R2Bucket;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		APP_ENV: "preview";
		ADMIN_AUTH_PROVIDER: "better-auth";
		BETTER_AUTH_URL: "https://sb-web-preview.yi-ding.workers.dev";
		BILLING_MODE: "disabled";
		EMAIL_MODE: "send";
		EMAIL_FROM: "AI.Engineer Sandbox <hello@mail.openboard.events>";
		EMAIL_ALLOWLIST: "yi.s.ding@gmail.com";
		EMAIL_FALLBACK_UI: "1";
		AIRTABLE_CRON: "0";
		NEXT_INC_CACHE_R2_PREFIX: "open-next-cache";
		R2_BUCKET_NAME: "sb-files-preview";
		TEST_AUTH: "1";
		WORKER_SELF_REFERENCE: Fetcher /* sb-web-preview */;
	}
	interface ProductionEnv {
		FILES: R2Bucket;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		APP_ENV: "production";
		ADMIN_AUTH_PROVIDER: "better-auth";
		BETTER_AUTH_URL: "https://sb-web.yi-ding.workers.dev";
		BILLING_MODE: "disabled";
		EMAIL_MODE: "send";
		EMAIL_FROM: "AI.Engineer Sandbox <hello@mail.openboard.events>";
		EMAIL_FALLBACK_UI: "0";
		AIRTABLE_CRON: "0";
		NEXT_INC_CACHE_R2_PREFIX: "open-next-cache";
		R2_BUCKET_NAME: "sb-files";
		WORKER_SELF_REFERENCE: Fetcher /* sb-web */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "ADMIN_AUTH_PROVIDER" | "BETTER_AUTH_URL" | "BILLING_MODE" | "EMAIL_MODE" | "EMAIL_FROM" | "EMAIL_ALLOWLIST" | "EMAIL_FALLBACK_UI" | "AIRTABLE_CRON" | "NEXT_INC_CACHE_R2_PREFIX" | "R2_BUCKET_NAME" | "TEST_AUTH">> {}
}
