import { z } from "zod";

export const SUBMISSION_STATUSES = ["draft", "pending", "accept_queue", "decline_queue", "accepted", "declined", "withdrawn"] as const;
export const SUBMISSION_KINDS = ["abstract", "session"] as const;
export const SUBMISSION_SOURCES = ["cfp", "manual", "import"] as const;
export const FORM_CONTEXTS = ["cfp", "portal"] as const;
export const FORM_STATUSES = ["draft", "open", "closed"] as const;
export const FIELD_TYPES = ["text", "textarea", "richtext", "dropdown", "multiselect", "radio", "checkbox", "email", "phone", "url", "number", "date", "file"] as const;
export const COMMITTED_FIELD_TYPES = ["text", "textarea", "richtext", "dropdown", "multiselect", "email", "url", "file"] as const;
export const PARTICIPANT_ROLES = ["speaker", "co_speaker", "moderator", "panelist"] as const;
export const CONFIRMATION_STATUSES = ["unconfirmed", "confirmed", "declined"] as const;
export const MEMBER_ROLES = ["owner", "organizer", "reviewer"] as const;
export const TASK_TARGETS = ["contact", "submission"] as const;
export const TASK_MODES = ["manual", "form", "file_request"] as const;
export const COMPLETION_VIAS = ["manual", "form_response", "file_upload", "admin"] as const;
export const SESSION_STATUSES = ["draft", "published"] as const;
export const PLAN_STATUSES = ["open", "closed"] as const;
export const EMBED_CONTENT_TYPES = ["agenda", "session_list", "schedule_itinerary", "speaker_list", "speaker_gallery"] as const;
export const TEMPLATE_KEYS = ["submission_received", "submission_accepted", "submission_declined", "task_assigned", "task_reminder", "schedule_assigned", "schedule_changed", "portal_login"] as const;
export const COMM_STATUSES = ["queued", "sent", "failed", "skipped"] as const;
export const ICS_METHODS = ["request", "cancel"] as const;
export const TOKEN_PURPOSES = ["magic_link", "ics_download", "impersonation"] as const;
export const FILE_KINDS = ["logo", "background", "headshot", "attachment", "slide", "upload"] as const;
export const CONDITION_OPS = ["eq", "neq", "in", "not_in", "answered", "empty"] as const;

export const submissionStatusSchema = z.enum(SUBMISSION_STATUSES);
export const submissionKindSchema = z.enum(SUBMISSION_KINDS);
export const submissionSourceSchema = z.enum(SUBMISSION_SOURCES);
export const formContextSchema = z.enum(FORM_CONTEXTS);
export const formStatusSchema = z.enum(FORM_STATUSES);
export const fieldTypeSchema = z.enum(FIELD_TYPES);
export const participantRoleSchema = z.enum(PARTICIPANT_ROLES);
export const confirmationStatusSchema = z.enum(CONFIRMATION_STATUSES);
export const memberRoleSchema = z.enum(MEMBER_ROLES);
export const taskTargetSchema = z.enum(TASK_TARGETS);
export const taskModeSchema = z.enum(TASK_MODES);
export const completionViaSchema = z.enum(COMPLETION_VIAS);
export const sessionStatusSchema = z.enum(SESSION_STATUSES);
export const planStatusSchema = z.enum(PLAN_STATUSES);
export const embedContentTypeSchema = z.enum(EMBED_CONTENT_TYPES);
export const templateKeySchema = z.enum(TEMPLATE_KEYS);
export const commStatusSchema = z.enum(COMM_STATUSES);
export const icsMethodSchema = z.enum(ICS_METHODS);
export const tokenPurposeSchema = z.enum(TOKEN_PURPOSES);
export const fileKindSchema = z.enum(FILE_KINDS);
export const conditionOpSchema = z.enum(CONDITION_OPS);

export type SubmissionStatus = z.infer<typeof submissionStatusSchema>;
export type SubmissionKind = z.infer<typeof submissionKindSchema>;
export type SubmissionSource = z.infer<typeof submissionSourceSchema>;
export type FormContext = z.infer<typeof formContextSchema>;
export type FormStatus = z.infer<typeof formStatusSchema>;
export type FieldType = z.infer<typeof fieldTypeSchema>;
export type ParticipantRole = z.infer<typeof participantRoleSchema>;
export type ConfirmationStatus = z.infer<typeof confirmationStatusSchema>;
export type MemberRole = z.infer<typeof memberRoleSchema>;
export type TaskTarget = z.infer<typeof taskTargetSchema>;
export type TaskMode = z.infer<typeof taskModeSchema>;
export type CompletionVia = z.infer<typeof completionViaSchema>;
export type SessionStatus = z.infer<typeof sessionStatusSchema>;
export type PlanStatus = z.infer<typeof planStatusSchema>;
export type EmbedContentType = z.infer<typeof embedContentTypeSchema>;
export type TemplateKey = z.infer<typeof templateKeySchema>;
export type CommStatus = z.infer<typeof commStatusSchema>;
export type IcsMethod = z.infer<typeof icsMethodSchema>;
export type TokenPurpose = z.infer<typeof tokenPurposeSchema>;
export type FileKind = z.infer<typeof fileKindSchema>;
export type ConditionOp = z.infer<typeof conditionOpSchema>;

// Temporary name retained for the merged demo adapter while server consumers
// use the canonical CONDITION_OPS name.
export const CONDITION_OPERATORS = CONDITION_OPS;
export type ConditionOperator = ConditionOp;
