"use client";

import { Check, Download, Mail, MoreHorizontal, Plus, Search, Star, UserRound, X } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useDemo, speakerName } from "@/shared/demo/demo-provider";
import type { SubmissionRecord } from "@/shared/demo/types";
import { formatInZone } from "@/shared/lib/time";
import type { SubmissionStatus } from "@/shared/contracts";
import { Avatar, Button, Drawer, Field, Modal, PageHeader, StatusBadge } from "@/shared/ui/ui-kit";
import { useToast } from "@/shared/ui/toast";

const filters: Array<{ id: "all" | SubmissionStatus; label: string }> = [{ id: "all", label: "All abstracts" }, { id: "pending", label: "Pending" }, { id: "accept_queue", label: "Accept queue" }, { id: "accepted", label: "Accepted" }, { id: "declined", label: "Declined" }, { id: "draft", label: "Drafts" }];

export function AbstractsPage({ eventId }: { eventId: string }) {
  const { state, dispatch } = useDemo(); const { toast } = useToast();
  const submissions = useMemo(() => state.submissions.filter((item) => item.eventId === eventId), [state.submissions, eventId]);
  const [status, setStatus] = useState<"all" | SubmissionStatus>("all"); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [openId, setOpenId] = useState<string | null>(null); const [adding, setAdding] = useState(false); const [confirmingDecisions, setConfirmingDecisions] = useState(false); const [newTitle, setNewTitle] = useState(""); const [newSpeaker, setNewSpeaker] = useState(state.speakers[0]?.id ?? "");
  const rows = useMemo(() => submissions.filter((item) => (status === "all" || item.status === status) && (`${item.code} ${item.title} ${item.track}`.toLowerCase().includes(search.toLowerCase()) || item.speakerIds.some((id) => speakerName(state.speakers.find((speaker) => speaker.id === id)).toLowerCase().includes(search.toLowerCase())))), [search, state.speakers, submissions, status]);
  const active = submissions.find((item) => item.id === openId) ?? null;
  const counts = (key: "all" | SubmissionStatus) => key === "all" ? submissions.length + 235 : submissions.filter((item) => item.status === key).length + (key === "pending" ? 10 : key === "accepted" ? 74 : key === "declined" ? 95 : key === "draft" ? 8 : key === "accept_queue" ? 28 : 0);
  function applyStatus(next: SubmissionStatus) { selected.forEach((submissionId) => dispatch({ type: "UPDATE_SUBMISSION", submissionId, patch: { status: next, updatedAt: new Date().toISOString() } })); toast(`${selected.length} abstract${selected.length === 1 ? "" : "s"} moved to ${next.replace("_", " ")}`); setSelected([]); }
  // Finalizes queued decisions, then notifies each (submission, speaker) pair
  // at most once — the deterministic communication id is the idempotency key.
  function processDecisions() {
    setConfirmingDecisions(false);
    const toFinalize = submissions.filter((item) => item.status === "accept_queue" || item.status === "decline_queue");
    toFinalize.forEach((item) => dispatch({ type: "UPDATE_SUBMISSION", submissionId: item.id, patch: { status: item.status === "accept_queue" ? "accepted" : "declined", updatedAt: new Date().toISOString() } }));
    const decided = submissions.map((item) => item.status === "accept_queue" ? { ...item, status: "accepted" as const } : item.status === "decline_queue" ? { ...item, status: "declined" as const } : item).filter((item) => item.status === "accepted" || item.status === "declined");
    let queued = 0;
    for (const submission of decided) for (const speakerId of submission.speakerIds) {
      const speaker = state.speakers.find((item) => item.id === speakerId);
      const commId = `decision_${submission.id}_${speakerId}`;
      if (!speaker || state.communications.some((item) => item.id === commId)) continue;
      const accepted = submission.status === "accepted";
      dispatch({ type: "ADD_COMMUNICATION", communication: { id: commId, eventId: submission.eventId, recipient: speaker.email, subject: accepted ? "You’re speaking at AI Engineer World’s Fair!" : "An update on your AI Engineer proposal", template: accepted ? "Decision — accepted" : "Decision — declined", status: "sent", sentAt: new Date().toISOString(), preview: accepted ? "Great news—your proposal has been accepted…" : "Thank you for submitting. After careful review…" } });
      queued += 1;
    }
    toast(queued > 0 ? `${toFinalize.length} queued decision${toFinalize.length === 1 ? "" : "s"} finalized · ${queued} email${queued === 1 ? "" : "s"} sent` : "All decisions were already notified — nothing to send");
  }
  function addAbstract() { if (!newTitle.trim() || !newSpeaker) return; const submission: SubmissionRecord = { id: `sub_${Date.now()}`, code: `SESS-${submissions.length + 101}`, eventId, formId: state.forms.find((form) => form.eventId === eventId)?.id ?? "", title: newTitle, type: "Talk · 30 min", status: "pending", speakerIds: [newSpeaker], track: "Unrouted", format: "Talk · 30 min", tags: [], submittedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), abstract: "Added manually by the organizing team.", audience: "", takeaways: "", answers: { title: newTitle }, score: null, reviewCount: 0 }; dispatch({ type: "ADD_SUBMISSION", submission }); setAdding(false); setNewTitle(""); toast(`${submission.code} created`); }
  function exportCsv() { const csv = ["Code,Title,Speaker,Status,Track,Score", ...rows.map((item) => [item.code, csvCell(item.title), csvCell(speakerName(state.speakers.find((speaker)=>speaker.id===item.speakerIds[0]))), item.status, csvCell(item.track), item.score ?? ""].join(","))].join("\n"); const blob = new Blob(["\ufeff", csv], {type:"text/csv"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download="abstracts-ai-engineer.csv"; a.click(); URL.revokeObjectURL(url); }
  return <><PageHeader eyebrow="PROGRAM" title="Abstracts" description="Review, score, route, and decide on every proposal." actions={<><Button variant="secondary" onClick={exportCsv}><Download size={16}/> Export CSV</Button><Button onClick={()=>setAdding(true)}><Plus size={16}/> Add abstract</Button></>} />
    <div className="abstract-status-tabs">{filters.map((filter)=><button key={filter.id} className={status===filter.id?"active":""} onClick={()=>setStatus(filter.id)}>{filter.label}<span>{counts(filter.id)}</span></button>)}</div>
    <section className="panel data-panel"><div className="data-toolbar"><label className="table-search"><Search size={16}/><input aria-label="Search titles, speakers, or SESS number" value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search titles, speakers, or SESS-#"/>{search && <button type="button" aria-label="Clear abstract search" onClick={()=>setSearch("")}><X size={14}/></button>}</label><span className="row-count">{rows.length} shown</span></div>{selected.length > 0 && <div className="bulk-bar"><span><b>{selected.length}</b> selected</span><Button size="sm" variant="secondary" onClick={()=>applyStatus("accept_queue")}><Check size={14}/> Accept queue</Button><Button size="sm" variant="secondary" onClick={()=>applyStatus("declined")}>Decline</Button><button onClick={()=>setSelected([])}>Clear</button></div>}<div className="table-scroll"><table className="data-table abstracts-table"><thead><tr><th><input type="checkbox" aria-label="Select all abstracts" checked={rows.length>0&&selected.length===rows.length} onChange={(event)=>setSelected(event.target.checked?rows.map((item)=>item.id):[])} /></th><th>ID</th><th>Title & speaker</th><th>Status</th><th>Track</th><th>Rating</th><th>Submitted</th><th/></tr></thead><tbody>{rows.map((submission)=><tr key={submission.id} className={selected.includes(submission.id)?"selected":""} onClick={()=>setOpenId(submission.id)}><td onClick={(event)=>event.stopPropagation()}><input type="checkbox" aria-label={"Select " + submission.code} checked={selected.includes(submission.id)} onChange={(event)=>setSelected((current)=>event.target.checked?[...current,submission.id]:current.filter((id)=>id!==submission.id))}/></td><td><b className="submission-code">{submission.code}</b></td><td><div className="submission-title-cell"><b>{submission.title}</b><span>{submission.speakerIds.map((id)=>speakerName(state.speakers.find((speaker)=>speaker.id===id))).join(", ")} · {submission.format}</span></div></td><td><StatusBadge value={submission.status}/></td><td><span className="track-chip">{submission.track}</span></td><td>{submission.score ? <span className="rating"><Star size={13} fill="currentColor"/>{submission.score.toFixed(1)}<small>({submission.reviewCount})</small></span>:<span className="dash">—</span>}</td><td><span className="table-date">Aug {7-(Number(submission.id.slice(-1))%5)}<small>2026</small></span></td><td><button type="button" className="icon-button" aria-label={"Open " + submission.code} onClick={(event)=>{event.stopPropagation();setOpenId(submission.id)}}><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table></div><div className="table-footer"><span>Showing {rows.length} of 247 abstracts</span></div></section>
    <div className="notify-bar"><div><span className="metric-icon accent"><Mail size={18}/></span><p><b>Ready to share decisions?</b><small>Finalizes the accept and decline queues, then emails each decision exactly once.</small></p></div><Button onClick={()=>setConfirmingDecisions(true)}>Process decisions & notify</Button></div>
    <SubmissionDrawer submission={active} onClose={()=>setOpenId(null)} onStatus={(next)=>{if(active)dispatch({type:"UPDATE_SUBMISSION",submissionId:active.id,patch:{status:next,updatedAt:new Date().toISOString()}});toast(`Status updated to ${next.replace("_"," ")}`);}} />
    <Modal open={confirmingDecisions} onClose={()=>setConfirmingDecisions(false)} title="Notify speakers?" description="Review this event-wide action before sending." footer={<><Button variant="secondary" onClick={()=>setConfirmingDecisions(false)}>Cancel</Button><Button onClick={processDecisions}>Finalize & send</Button></>}>
      <p className="long-copy">
        This will finalize {submissions.filter((item) => item.status === "accept_queue" || item.status === "decline_queue").length} queued decisions and send each affected speaker one decision email. Already-notified decisions will not be sent again.
      </p>
    </Modal>
    <Modal open={adding} onClose={()=>setAdding(false)} title="Add an abstract" description="Create a proposal on behalf of a speaker." footer={<><Button variant="secondary" onClick={()=>setAdding(false)}>Cancel</Button><Button disabled={!newTitle.trim()} onClick={addAbstract}>Create abstract</Button></>}><div className="form-stack"><Field label="Session title" required><input autoFocus value={newTitle} onChange={(e)=>setNewTitle(e.target.value)} placeholder="Enter a clear session title"/></Field><Field label="Primary speaker" required><select value={newSpeaker} onChange={(e)=>setNewSpeaker(e.target.value)}>{state.speakers.map((speaker)=><option value={speaker.id} key={speaker.id}>{speakerName(speaker)} · {speaker.company}</option>)}</select></Field><Field label="Source"><input value="Manual entry" disabled/></Field></div></Modal>
  </>;
}

function SubmissionDrawer({ submission, onClose, onStatus }: { submission: SubmissionRecord|null; onClose:()=>void; onStatus:(status:SubmissionStatus)=>void }) {
  const { state }=useDemo(); const [tab,setTab]=useState<"overview"|"answers"|"reviews"|"activity">("overview"); if(!submission)return null; const speaker=state.speakers.find((item)=>item.id===submission.speakerIds[0]); const reviews=state.reviews.filter((item)=>item.submissionId===submission.id); const timezone=state.events.find((event)=>event.id===submission.eventId)?.timezone??"UTC";
  return <Drawer open={Boolean(submission)} onClose={onClose} title={submission.code}><div className="submission-drawer"><div className="drawer-hero"><div><StatusBadge value={submission.status}/><h2>{submission.title}</h2><p>{submission.format} · {submission.track}</p></div><div className="drawer-decisions"><button onClick={()=>onStatus("declined")}>Decline</button><button onClick={()=>onStatus("accept_queue")}><Check size={15}/> Add to accept queue</button></div></div><div className="drawer-tabs">{(["overview","answers","reviews","activity"] as const).map((item)=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}{item==="reviews"&&<span>{submission.reviewCount}</span>}</button>)}</div>{tab==="overview"&&<div className="drawer-content"><section className="speaker-card"><Avatar initials={speaker?.avatar??"?"} color={speaker?.avatarColor}/><div><b>{speakerName(speaker)}</b><span>{speaker?.title} at {speaker?.company}</span><a href={`mailto:${speaker?.email}`}>{speaker?.email}</a></div><Link className="button button-secondary button-sm" href={"/events/" + submission.eventId + "/speakers?contactId=" + (speaker?.id ?? "")}><UserRound size={14}/> Profile</Link></section><section><h3>Abstract</h3><p className="long-copy">{submission.abstract}</p></section><section><h3>Audience</h3><p className="long-copy">{submission.audience}</p></section><section><h3>Takeaways</h3><p className="long-copy">{submission.takeaways}</p></section><div className="routing-summary"><div><span>Track</span><b>{submission.track}</b></div><div><span>Format</span><b>{submission.format}</b></div><div><span>Tags</span><b>{submission.tags.join(", ")||"—"}</b></div></div></div>}{tab==="answers"&&<div className="drawer-content"><div className="pinned-note"><LockKeyholeIcon/> Answers from form version 7</div>{Object.entries(submission.answers).map(([key,value])=><section className="answer-row" key={key}><h3>{titleCase(key)}</h3><p>{Array.isArray(value)?value.join(", "):String(value)}</p></section>)}</div>}{tab==="reviews"&&<div className="drawer-content"><div className="review-score-summary"><Star size={22} fill="currentColor"/><strong>{submission.score?.toFixed(1)??"—"}</strong><span>Average from {submission.reviewCount} reviews</span></div>{reviews.map((review)=><article className="review-comment" key={review.id}><header><span>{review.reviewer.slice(0,2).toUpperCase()}</span><b>{review.reviewer}</b><em>{review.score}/5</em></header><p>{review.note}</p></article>)}</div>}{tab==="activity"&&<div className="drawer-content activity-list"><div><span/><p><b>Submission updated</b><small>August 7 at 11:30 AM</small></p></div><div><span/><p><b>Routed to {submission.track}</b><small>Matched rule “Agent sessions”</small></p></div><div><span/><p><b>Proposal received</b><small>{formatInZone(submission.submittedAt,timezone,{month:"long",day:"numeric",year:"numeric",timeZoneName:"short"})}</small></p></div></div>}</div></Drawer>;
}
function LockKeyholeIcon(){return <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>}
function titleCase(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase())}
function csvCell(value:string){return `"${value.replaceAll('"','""').replace(/^[=+\-@\t\r]/, "'$&")}"`}
